REM rcoco_case1
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case1\forensics_case1_test_00000-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case1/out01.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case1\forensics_case1_test_00002-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case1/out03.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case1\forensics_case1_test_00001-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case1/out02.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case1\forensics_case1_test_00003-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case1/out04.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case1\forensics_case1_test_00004-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case1/out05.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case1\forensics_case1_test_00005-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case1/out06.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case1\forensics_case1_test_00006-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case1/out07.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case1\forensics_case1_test_00007-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case1/out08.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case1\forensics_case1_test_00008-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case1/out09.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case1\forensics_case1_test_00009-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case1/out10.txt --tfrecord

REM rcoco_case2
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case2\forensics_case2_test_00000-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case2/out01.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case2\forensics_case2_test_00002-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case2/out03.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case2\forensics_case2_test_00001-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case2/out02.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case2\forensics_case2_test_00003-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case2/out04.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case2\forensics_case2_test_00004-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case2/out05.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case2\forensics_case2_test_00005-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case2/out06.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case2\forensics_case2_test_00006-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case2/out07.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case2\forensics_case2_test_00007-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case2/out08.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case2\forensics_case2_test_00008-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case2/out09.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\rcoco_case2\forensics_case2_test_00009-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\rcoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/rcoco_case2/out10.txt --tfrecord

REM ccoco_case1
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case1\forensics_case1_test_00000-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case1/out01.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case1\forensics_case1_test_00002-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case1/out03.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case1\forensics_case1_test_00001-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case1/out02.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case1\forensics_case1_test_00003-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case1/out04.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case1\forensics_case1_test_00004-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case1/out05.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case1\forensics_case1_test_00005-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case1/out06.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case1\forensics_case1_test_00006-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case1/out07.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case1\forensics_case1_test_00007-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case1/out08.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case1\forensics_case1_test_00008-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case1/out09.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case1\forensics_case1_test_00009-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case1/out10.txt --tfrecord

REM ccoco_case2
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case2\forensics_case2_test_00000-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case2/out01.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case2\forensics_case2_test_00002-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case2/out03.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case2\forensics_case2_test_00001-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case2/out02.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case2\forensics_case2_test_00003-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case2/out04.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case2\forensics_case2_test_00004-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case2/out05.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case2\forensics_case2_test_00005-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case2/out06.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case2\forensics_case2_test_00006-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case2/out07.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case2\forensics_case2_test_00007-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case2/out08.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case2\forensics_case2_test_00008-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case2/out09.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\ccoco_case2\forensics_case2_test_00009-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\ccoco_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/ccoco_case2/out10.txt --tfrecord

REM glcm_case1
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case1\forensics_case1_test_00000-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case1/out01.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case1\forensics_case1_test_00002-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case1/out03.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case1\forensics_case1_test_00001-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case1/out02.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case1\forensics_case1_test_00003-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case1/out04.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case1\forensics_case1_test_00004-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case1/out05.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case1\forensics_case1_test_00005-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case1/out06.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case1\forensics_case1_test_00006-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case1/out07.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case1\forensics_case1_test_00007-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case1/out08.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case1\forensics_case1_test_00008-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case1/out09.txt --tfrecord
REM python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case1\forensics_case1_test_00009-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case1_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case1/out10.txt --tfrecord

REM glcm_case2
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case2\forensics_case2_test_00000-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case2/out01.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case2\forensics_case2_test_00002-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case2/out03.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case2\forensics_case2_test_00001-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case2/out02.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case2\forensics_case2_test_00003-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case2/out04.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case2\forensics_case2_test_00004-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case2/out05.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case2\forensics_case2_test_00005-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case2/out06.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case2\forensics_case2_test_00006-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case2/out07.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case2\forensics_case2_test_00007-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case2/out08.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case2\forensics_case2_test_00008-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case2/out09.txt --tfrecord
python classify_image.py --num_classes 2 --infile "C:\tmp\data\forensics\case2\forensics_case2_test_00009-of-00010.tfrecord" --model_name inception_resnet_v2 --preprocessing_name inception_resnet_v2_notcrop --checkpoint_path C:\tmp\checkpoints\glcm_case2_fulltrain_ckpt\model.ckpt-5000 --outfile C:/tmp/data/forensics/case2/out10.txt --tfrecord
